service: zapier2bms

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 256

functions:
  RegisterOpportunity:
    handler: handler.RegisterOpportunity

    events:
      - http:
          path: regopp/submit
          method: post

    environment: ${file(env.yml)}
